#!/bin/sh

cd "$(dirname "$0")"

. "$PWD"/settings

# Destroy any previous container.
docker stop "$NANO_CONTAINER" >&- 2>&-
docker rm "$NANO_CONTAINER" >&- 2>&-

docker run -it --name="$NANO_CONTAINER" "$NANO_IMAGE"
